---
name: Parser
version: 1.0.0.0

license: MIT
license-file: LICENSE

dependencies:
  - bytestring
  - relude
  - base
  - random

library:
  source-dirs: ./app

ghc-options:
  - -fwrite-ide-info
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Widentities
  - -Wredundant-constraints
  - -Wcpp-undef
  - -Wunused-packages

executables:
  hello:
    main: Main.hs
    source-dirs: ./app/
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

